<?php

/**
 * @file
 * Contains qr_generator.module..
 */

require_once __DIR__ . '/vendor/autoload.php';

use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\qr_generator\Entity\QRGenerator;
use Drupal\taxonomy\Entity\Vocabulary;
use Drupal\user\Entity\Role;
use Drupal\user\Entity\User;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function qr_generator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qr_generator module.
    case 'help.page.qr_generator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for creating QR codes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_cron().
 */
function qr_generator_cron() {
  $qr_codes = QRGenerator::loadMultiple();
  $statuses = array();

  // Collect statuses and ID's
  foreach ($qr_codes as $qr_code) {
    $qr_code->setURLStatus();
    $statuses[$qr_code->id()] = $qr_code->getURLStatus();
	}
  qr_generator_send_status_mail($statuses);
}

function qr_generator_send_status_mail($statuses) {
  $failed = array();
  $to = '';

  $ids = \Drupal::entityQuery('user')
  ->condition('status', 1)
  ->condition('roles', 'qr_admin')
  ->execute();
  $users = User::loadMultiple($ids);

  foreach ($users as $user) {
    $to .= $user->getEmail() . ',';
  }

  foreach ($statuses as $id => $status) {
    if ($status == 'FAILED') {
      $entity = QRGenerator::load($id);
      $failed[$id] = $entity->getName();
    }
  }

  if (!empty($failed)) {
    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'qr_generator';
    $key = 'qr_code_status_failed';
    $langcode = \Drupal::currentUser()->getPreferredLangcode();
    $params['failed'] = $failed;
    $mailManager->mail($module, $key, $to, $langcode, $params, $send = FALSE);
  }
}

/**
 * Implements hook_mail().
 */
function qr_generator_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
  case 'qr_code_status_failed':
    $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
    $message['subject'] = t('Some QR code failed validation');
    $message['body'][] = SafeMarkup::checkPlain(t('The following QR codes failed:<br />'));
    $url = \Drupal::request()->getHost();;
    $message['body'][] = SafeMarkup::checkPlain('<ul>');
    foreach ($params['failed'] as $id => $title) {
      $message['body'][] = SafeMarkup::checkPlain('<li><a href="http://' . $url . '/admin/structure/qr_generator/' . $id . '/edit' . '">' . $title . "</a></li>");
    }
    $message['body'][] = SafeMarkup::checkPlain('</ul>');
    break;
  }
}

function qr_generator_qr_generator_insert(QRGenerator $entity) {
  $entity->generateQR();
}

function qr_generator_generate_image($msg, $back_color, $fore_color) {
  $msg = \Drupal::request()->getHost() . $msg;
  $back_color = hexdec(str_replace('#', '', $back_color));
  $fore_color = hexdec(str_replace('#', '', $fore_color));

  ob_start();
  QRCode::png($msg, false, QR_ECLEVEL_L, 3, 1, FALSE, $back_color, $fore_color);
  $source_data = ob_get_contents();
  ob_end_clean();

  ob_start();
  header('Content-Type: image/png');

  $source_img = imagecreatefromstring($source_data);
  $old_w = imagesx($source_img);
  $old_h = imagesy($source_img);
  $size = 200;
  $dest_img = imagecreatetruecolor($size, $size);

  imagecopyresampled($dest_img, $source_img, 0, 0, 0, 0, $size, $size, $old_w, $old_h);
  imagepng($dest_img);
  imagedestroy($dest_img);

  $content = ob_get_contents();
  ob_end_clean();

  return $content;
}

function qr_generator_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'qr_generator/icons';
}

function qr_generator_add_logo_2_qr($qr_img_obj, $qr_logo_obj) {

	ob_start();
	header('Content-type: image/png');

	$QR = imagecreatefromstring(file_get_contents($qr_img_obj->getFileUri()));
	$logo = imagecreatefromstring(file_get_contents($qr_logo_obj->getFileUri()));

	$QR_width = imagesx($QR);
	$QR_height = imagesy($QR);
	$logo_width = imagesx($logo);
	$logo_height = imagesy($logo);

	// Scale logo to fit in the QR Code
	if ($logo_width >= $logo_height) {
		$logo_qr_width = $QR_width / 2.3;
		$scale = $logo_width / $logo_qr_width;
		$logo_qr_height = $logo_height / $scale;
	} else {
		$logo_qr_height = $QR_height / 2.3;
		$scale = $logo_height / $logo_qr_height;
		$logo_qr_width = $logo_width / $scale;
	}

	imagecopyresampled(
		$QR, $logo,
		(($QR_width / 2) - ($logo_qr_width / 2)),
		(($QR_height / 2) - ($logo_qr_height / 2)),
		0, 0,
		$logo_qr_width, $logo_qr_height, $logo_width, $logo_height
	);

	imagepng($QR);
	imagedestroy($QR);

	$img_stream = ob_get_contents();
	ob_end_clean();

	$file = file_save_data($img_stream, $qr_img_obj->getFileUri());
	return $file;
}

/**
 * Implements hook_toolbar().
 */
function qr_generator_toolbar() {
    $items = array();

    $items['qr_admin'] = array(
        '#type' => 'toolbar_item',
        'tab' => array(
            '#type' => 'link',
            '#title' => t('QR Admin'),
            '#url' => Url::fromRoute('qr_generator.admin'),
            '#options' => array(
                'attributes' => array(
                    'title' => t('QR Admin'),
                    'class' => array('toolbar-icon', 'toolbar-item', 'toolbar-icon-qr'),
                ),
            ),
        ),
    );

    return $items;
}

/**
 * Implements hook_toolbar_alter().
 */
function qr_generator_toolbar_alter(&$items) {
  $account = Drupal::currentUser()->getAccount();
  $roles = $account->getRoles();

  if (in_array('qr_admin', $roles) or in_array('qr_editor', $roles)) {
    if (!in_array('administrator', $roles)) {
      unset($items['administration']);
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function qr_generator_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'qr_generator_add_form') {
    unset($form['incoming_url']['widget'][0]['uri']['#description']);
    unset($form['outgoing_url']['widget'][0]['uri']['#description']);
  }
 if ($form_id == 'qr_generator_edit_form') {
   unset($form['incoming_url']['widget'][0]['uri']['#description']);
   unset($form['outgoing_url']['widget'][0]['uri']['#description']);
 }
}

function qr_generator_install() {
  // Create QR Admin and QR Editor role
  $roles = Role::loadMultiple();

  $rid = 'qr_editor';
  if (!isset($roles[$rid])) {
    $editor_role = Role::create(array(
      'id' => 'qr_editor',
      'label' => 'QR Editor'
    ));
    $editor_role->save();
  }

  $rid = 'qr_admin';
  if (!isset($roles[$rid])) {
    $admin_role = Role::create(array(
      'id' => 'qr_admin',
      'label' => 'QR Admin'
    ));
    $admin_role->save();
  }

  // Create QR category vocabulary
  $vid = 'qr_generator_category';
  $name = 'QR Category';
  $vocabularies = Vocabulary::loadMultiple();
  if (!isset($vocabularies[$vid])) {
    $vocabulary = Vocabulary::create(array(
          'vid' => $vid,
          'machine_name' => $vid,
          'name' => $name,
    ));
    $vocabulary->save();
  }
}
