<?php

/**
 * @file
 * Contains qr_generator.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function qr_generator_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the qr_generator module.
    case 'help.page.qr_generator':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Module for creating QR codes') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_presave();
 */
function qr_generator_entity_presave(\Drupal\qr_generator\Entity\QRGenerator $entity) {
  if ($entity->isNew()) {
    $url = str_replace(' ', '-', $entity->getName());
    $url = str_replace(array('æ', 'ø', 'å', ' '), array('ae', 'oe', 'aa', '-'), $entity->getName());
    $url = preg_replace('/[^A-Za-z0-9\-]/', '', $url);
    $url = strtolower($url);
    $entity->setIncomingURL($url);
  }
}
